# Generated by Django 4.1.3 on 2022-12-12 09:33

from django.db import migrations, models
import helpers.generator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=helpers.generator.Token_Generator, max_length=40),
        ),
    ]
