# Generated by Django 4.1.3 on 2022-12-22 09:22

from django.db import migrations, models
import django.db.models.deletion
import helpers.generator


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0023_plan'),
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='day_exp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='month_exp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rate.plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=helpers.generator.Token_Generator, max_length=40, unique=True),
        ),
    ]
