# Generated by Django 4.1.3 on 2022-12-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0023_plan'),
        ('users', '0003_remove_user_role_user_day_exp_user_month_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate.plan'),
        ),
    ]
