# Generated by Django 4.1.3 on 2022-12-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, choices=[('COMMON', 'common'), ('planA', 'a'), ('planB', 'b')], max_length=8, null=True),
        ),
    ]
