# Generated by Django 4.1.3 on 2022-12-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0024_rename_month_limit_plan_exp_date'),
        ('users', '0005_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('COMMON', 'common'), ('PREMIUM', 'premium')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate.plan'),
        ),
    ]
