# Generated by Django 4.1.3 on 2022-12-29 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role_alter_user_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day_exp',
        ),
        migrations.AddField(
            model_name='user',
            name='day_exp_begin',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 9, 12, 46, 227046)),
        ),
        migrations.AddField(
            model_name='user',
            name='dea_exp_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 9, 12, 46, 227046)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('COMMON', 'common'), ('PREMIUM', 'premium')], default='COMMON', max_length=8, null=True),
        ),
    ]
