# Generated by Django 4.1.3 on 2022-12-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_day_exp_user_day_exp_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_exp_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dea_exp_end',
            field=models.DateTimeField(null=True),
        ),
    ]
