# Generated by Django 4.1.3 on 2022-12-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_day_exp_begin_alter_user_dea_exp_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dea_exp_end',
            new_name='day_exp_end',
        ),
    ]
