# Generated by Django 4.1.3 on 2023-02-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
        ('users', '0009_rename_dea_exp_end_user_day_exp_end'),
    ]

    operations = [
    ]
