# Generated by Django 4.1.3 on 2023-02-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0024_rename_month_limit_plan_exp_date'),
        ('users', '0010_merge_20230221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='rate.plan'),
        ),
    ]
