# Generated by Django 4.1.3 on 2022-12-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=5)),
                ('name_2', models.CharField(max_length=5)),
                ('name_3', models.CharField(max_length=5)),
                ('name_4', models.CharField(max_length=5)),
            ],
        ),
    ]
