# Generated by Django 4.1.3 on 2022-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_remove_currency_country_currency_code_currency_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
