# Generated by Django 4.1.3 on 2022-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_alter_currency_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='updated_date',
            field=models.TimeField(),
        ),
    ]
