# Generated by Django 4.1.3 on 2022-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_alter_currency_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
