# Generated by Django 4.1.3 on 2022-12-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_alter_currency_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
                ('price', models.IntegerField()),
                ('rate', models.CharField(max_length=20)),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
