# Generated by Django 4.1.3 on 2022-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_gold_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
