# Generated by Django 4.1.3 on 2022-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_alter_gold_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('marketcap', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('daily_swing', models.FloatField()),
                ('weekly_swing', models.FloatField()),
                ('rank', models.IntegerField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
