# Generated by Django 4.1.3 on 2022-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_crypto_rial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='daily_swing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='weekly_swing',
            field=models.FloatField(default=0.0),
        ),
    ]
