# Generated by Django 4.1.3 on 2022-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0013_alter_crypto_daily_swing_alter_crypto_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='rial_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
