# Generated by Django 4.1.3 on 2022-12-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0014_alter_crypto_price_alter_crypto_rial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='daily_swing',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='rial_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='weekly_swing',
            field=models.FloatField(),
        ),
    ]
