# Generated by Django 4.1.3 on 2022-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_alter_crypto_daily_swing_alter_crypto_rial_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='daily_swing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='weekly_swing',
            field=models.IntegerField(),
        ),
    ]
