# Generated by Django 4.1.3 on 2022-12-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0017_alter_crypto_daily_swing_alter_crypto_weekly_swing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
