# Generated by Django 4.1.3 on 2022-12-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0018_alter_currency_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
