# Generated by Django 4.1.3 on 2022-12-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0019_currency_time_stamp_alter_currency_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='code',
            field=models.CharField(default='a', max_length=6),
        ),
    ]
