# Generated by Django 4.1.3 on 2022-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0020_crypto_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
