# Generated by Django 4.1.3 on 2022-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0022_alter_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('daily_request_limit', models.IntegerField()),
                ('month_limit', models.IntegerField()),
                ('currency', models.BooleanField()),
                ('gold', models.BooleanField()),
                ('crypto', models.BooleanField()),
            ],
        ),
    ]
