# Generated by Django 4.1.3 on 2022-12-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0023_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='month_limit',
            new_name='exp_date',
        ),
    ]
