# Generated by Django 4.1.3 on 2023-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0024_rename_month_limit_plan_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='status',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
